In [1]:
%matplotlib inline

In [2]:
import matplotlib
import numpy as np
import matplotlib.pyplot as plt

## Numpy. Повторение.

### Массивы

##### Одномерные массивы

In [3]:
a = np.array([1, 4, 5, 8], float)  # создание массива из списка
a

array([1., 4., 5., 8.])

In [4]:
type(a)

numpy.ndarray

In [5]:
a[:2] # срез

array([1., 4.])

In [6]:
a[3] # получение элемента по индексу

8.0

##### Многомерные массивы

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]], float) # создание двумерного массива

In [8]:
a[0,0] # получение значения элемента по индексам

1.0

In [9]:
a[1, :] # срез

array([4., 5., 6.])

In [10]:
a[:, 2] # срез

array([3., 6.])

In [11]:
a[-1:, -2:] # срез

array([[5., 6.]])

In [12]:
a.shape # количество строк и столбцов в матрице

(2, 3)

In [13]:
a.dtype # тип элементов массива

dtype('float64')

In [14]:
len(a) # длина первого измерения

2

In [15]:
0 in a # проверка наличия элемента

False

In [16]:
2 in a # проверка наличия элемента

True

In [17]:
a = np.array(range(10), float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
a = a.reshape((5, 2)) # изменение формы массива
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [19]:
b = a # присваивание ссылки на массив
c = a.copy() # копирование массива
a[0] = 1
a

array([[1., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [20]:
b

array([[1., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [21]:
c

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [22]:
a.tolist() # преобразование массива в список, состоящий из списков

[[1.0, 1.0], [2.0, 3.0], [4.0, 5.0], [6.0, 7.0], [8.0, 9.0]]

In [23]:
list(a) # преобразование массива в список массивов

[array([1., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8., 9.])]

In [24]:
s = a.tostring() # преобразование массива в бинарную строку
s

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @\x00\x00\x00\x00\x00\x00"@'

In [25]:
np.frombuffer(s) # преобразование бинарной строки в массив

array([1., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
a = np.array([1, 2, 3], float)
a

array([1., 2., 3.])

In [27]:
a.fill(0) # заполение массива одинаковыми элементами
a

array([0., 0., 0.])

In [28]:
a = np.array(range(6), float).reshape((2, 3))
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [29]:
a.transpose() # транспонирование матрицы

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
a.flatten() # 2d -> 1d

array([1., 2., 3., 4., 5., 6.])

In [32]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7, 8]], float)
np.concatenate((a, b)) #

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [33]:
a = np.array([1, 2, 3], float)
a

array([1., 2., 3.])

In [34]:
a[:, np.newaxis] # увеличение размерности массива

array([[1.],
       [2.],
       [3.]])

In [35]:
a[:, np.newaxis].shape

(3, 1)

##### Другие пути создания массивов

In [36]:
np.arange(5, dtype=float) # аналогична range, возвращает массив

array([0., 1., 2., 3., 4.])

In [37]:
np.ones((2, 3), dtype=float) # массив заполненный единицами

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.zeros((2, 3), dtype=int) # массив, хаполненный нулями

array([[0, 0, 0],
       [0, 0, 0]])

In [39]:
a = np.array([[1, 2, 3], [4, 5 ,6]], float)
np.zeros_like(a) # заполнение существующего массива нулями

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.ones_like(a) # заполнение текущего масива единицами

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.identity(4, dtype=float) # создание единичной матрицы

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.eye(4, k=1, dtype=float) # создание матрицы с едницами на k-й диагонали

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

##### Математические операции над массивами

In [43]:
a = np.array([1, 2, 3], float)
b = np.array([4, 5, 6], float)
a + b # сложение

array([5., 7., 9.])

In [44]:
a - b # вычитание

array([-3., -3., -3.])

In [45]:
a * b # умножение

array([ 4., 10., 18.])

In [46]:
b / a # деление

array([4. , 2.5, 2. ])

In [47]:
a % b # деление по модулю

array([1., 2., 3.])

In [48]:
b**a # возведение в степень

array([  4.,  25., 216.])

In [49]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[2, 0], [1, 3]], float)
a * b

array([[ 2.,  0.],
       [ 3., 12.]])

In [50]:
a = np.array([1, 2, 3], float)
b = np.array([4, 5], float)
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [51]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [52]:
a = np.zeros((2,2), float)
b = np.array([-1, 3], float)
a + b

array([[-1.,  3.],
       [-1.,  3.]])

In [53]:
a + b[np.newaxis,:]

array([[-1.,  3.],
       [-1.,  3.]])

In [54]:
a + b[:, np.newaxis]

array([[-1., -1.],
       [ 3.,  3.]])

##### Математические операции
##### abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, arctanh

In [55]:
a = np.array([1, 4, 9], float)
np.sqrt(a) # извлечение корня

array([1., 2., 3.])

In [56]:
a = np.array([1.1, 1.5, 1.9], float)
np.floor(a) # округление в меньшую сторону

array([1., 1., 1.])

In [57]:
np.ceil(a) # округление в большую сторону

array([2., 2., 2.])

In [58]:
np.rint(a) # округление до боижайшегоё

array([1., 2., 2.])

##### Математические константы, число пи и число е

In [59]:
np.pi

3.141592653589793

In [60]:
np.e

2.718281828459045

##### Перебор элементов массива

In [61]:
a = np.array([1, 4, 5], int)
for x in a:
    print(x)

1
4
5


In [62]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [63]:
for (x, y) in a:
    print(x * y)

2.0
12.0
30.0


##### Базовые операции над массивами

In [64]:
a = np.array([1, 2, 3], float)
a.sum() # суммирование всех элементов массива

6.0

In [65]:
a.prod() # перемножение всех элементов массива

6.0

In [66]:
np.sum(a) # аналог a.sum()

6.0

In [67]:
np.prod(a) # аналог a.prod()

6.0

In [68]:
a.mean() # медиана

2.0

In [69]:
a.var() # вариация

0.6666666666666666

In [70]:
a.std() # среднеквадратичное отклонение

0.816496580927726

In [71]:
a.min() # минимум

1.0

In [72]:
a.max() # максимум

3.0

In [73]:
a.argmin() # индекс минимального элемента

0

In [74]:
a.argmax() # индекс максимального элемента

2

In [75]:
sorted(a) # сортировка массива

[1.0, 2.0, 3.0]

In [76]:
a.sort() # in-place сортировка массива
a

array([1., 2., 3.])

In [77]:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0, 5) # "сокращение" значений, для того, чтобы они принадлежали определённому диапазону

array([5., 2., 5., 0., 0.])

In [78]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a) # уникальные элементы в массиве

array([1., 4., 5., 7.])

In [79]:
a = np.array([[1, 2], [3, 4]], float)
a.diagonal() # диагональ матрицы

array([1., 4.])

##### Операторы сравнения

In [80]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
a > b

array([ True, False, False])

In [81]:
a == b

array([False,  True, False])

In [82]:
a <= b

array([False,  True,  True])

In [83]:
c = a > b
c

array([ True, False, False])

In [84]:
a = np.array([1, 3, 0], float)
a > 2

array([False,  True, False])

In [85]:
c = np.array([True, False, False], bool)
any(c) # хотя бы олдин элемент равен истине

True

In [86]:
all(c) # все элементы истинны

False

In [87]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [88]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [89]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

In [90]:
a = np.array([1, 3, 0], float)
np.where(a != 0, 1 / a, a)  # where(boolarray, truearray, falsearray)

G:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([1.        , 0.33333333, 0.        ])

In [91]:
np.where(a > 0, 3, 2)

array([3, 3, 2])

In [92]:
a = np.array([[0, 1], [3, 0]], float)
a.nonzero() # кортеж индексов ненулевых значений

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

In [93]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)  # проверка на NaN

array([False,  True, False])

In [94]:
np.isfinite(a) # проверка на конечность

array([ True, False, False])

##### Выбор элементов массива и манипуляции с ними

In [95]:
a = np.array([[6, 4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]])

In [96]:
a[a >= 6] # фильтрация с помощью булевого массива

array([6., 9.])

In [97]:
sel = (a >= 6)
a[sel]

array([6., 9.])

In [98]:
a[np.logical_and(a > 5, a < 9)]  # фильтрация с помощью булевых выражений

array([6.])

In [99]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1 ,3, 2, 1], int)
a[b]  # целочисленный массив хранит индексы элементов, которые необходимо взять из массива

array([2., 2., 4., 8., 6., 4.])

In [100]:
a[[0, 0, 1, 3, 2, 1]]

array([2., 2., 4., 8., 6., 4.])

In [101]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b, c]

array([ 1.,  4., 16., 16.,  4.])

In [102]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a.take(b) # выполнение выборки с целочисленными массивами, аналог оператора взятия по индексу

array([2., 2., 4., 8., 6., 4.])

In [103]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([0, 0, 1], int)
a.take(b, axis=0)

array([[0., 1.],
       [0., 1.],
       [2., 3.]])

In [104]:
a = np.array([0, 1, 2, 3, 4, 5], float)
b = np.array([9, 8, 7], float)
a.put([0, 3], b) # берёт значения из массива a и записывает их в массив b на специфические индексы
a

array([9., 1., 2., 8., 4., 5.])

##### Векторная и матричная математика

In [105]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b) # скалярное произведение

5.0

In [106]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
np.dot(b, a) # перемножение матриц

array([ 6., 11.])

In [107]:
np.dot(a, b)

array([ 3., 13.])

In [108]:
np.dot(a, c)

array([[ 4.,  0.],
       [14.,  2.]])

In [109]:
np.dot(c, a)

array([[2., 4.],
       [0., 4.]])

In [110]:
a = np.array([1, 4, 0], float)
b = np.array([2, 2, 1], float)
np.outer(a, b) # внешнее произведение

array([[2., 2., 1.],
       [8., 8., 4.],
       [0., 0., 0.]])

In [111]:
np.inner(a, b) # скалярное произведение

10.0

In [112]:
np.cross(a, b) # тензорное произведение

array([ 4., -1., -6.])

In [113]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
a

array([[4., 2., 0.],
       [9., 3., 7.],
       [1., 2., 1.]])

In [114]:
np.linalg.det(a) # определитель матрицы

-48.00000000000003

In [115]:
vals, vecs = np.linalg.eig(a) # собственные значения и собственный вектор матрицы
vals

array([ 8.85591316,  1.9391628 , -2.79507597])

In [116]:
vecs

array([[-0.3663565 , -0.54736745,  0.25928158],
       [-0.88949768,  0.5640176 , -0.88091903],
       [-0.27308752,  0.61828231,  0.39592263]])

In [117]:
b = np.linalg.inv(a) #поиск невырожденной матрицы
b

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [118]:
np.dot(a, b)

array([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [119]:
a = np.array([[1, 3,4], [5, 2, 3]], float)
U, s, Vh = np.linalg.svd(a) # SVD разложение матрицы, аналог диагонализации неквадратной матрицы
U

array([[-0.6113829 , -0.79133492],
       [-0.79133492,  0.6113829 ]])

In [120]:
s

array([7.46791327, 2.86884495])

In [121]:
Vh

array([[-0.61169129, -0.45753324, -0.64536587],
       [ 0.78971838, -0.40129005, -0.46401635],
       [-0.046676  , -0.79349205,  0.60678804]])

##### Математика многочленов

In [122]:
np.poly([-1, 1, 1, 10]) # получение коэффициентов многочлена по его известным корням

array([  1., -11.,   9.,  11., -10.])

In [123]:
np.roots([1, 4, -2, 3]) # получение корней многочлена по коэффициентам

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

In [124]:
np.polyint([1, 1, 1, 1]) # интегрирование коэффициентов многочлена

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

In [125]:
np.polyder([1./4., 1./3., 1./2., 1., 0.]) # аналогично, дифференцирование

array([1., 1., 1., 1.])

In [126]:
np.polyval([1, -2, 0, 2], 4) # подставляет в многочлен заданное значение, также есть polyadd, polysub, polymul, polydiv

34

In [127]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0, 2, 1, 3, 7, 10, 11, 19]
np.polyfit(x, y, 2) # интерполяция многочлена заданного порядка к набору значений

array([ 0.375     , -0.88690476,  1.05357143])

##### Статистика

In [128]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
np.median(a) # поиск медианы

3.0

In [129]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
c = np.corrcoef(a)
c # поиск корреляционной матрицы

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [130]:
np.cov(a) # поиск ковариационной матрицы

array([[0.91666667, 2.08333333],
       [2.08333333, 8.91666667]])

##### Случайные числа

In [131]:
np.random.seed(293423)  # задть seed для генерации последовательности случайных чисел

In [132]:
np.random.rand(5) # массив случайных чисел из полуинтервала [0, 1)

array([0.33677247, 0.52693437, 0.79529578, 0.78867702, 0.02147624])

In [133]:
np.random.rand(2,3) # генерация двумерного маассива

array([[0.84612516, 0.0704939 , 0.1526965 ],
       [0.77831701, 0.80821151, 0.82198398]])

In [134]:
np.random.rand(6).reshape((2,3)) # использование reshape

array([[0.90239653, 0.8385685 , 0.02638565],
       [0.33681448, 0.46480928, 0.61686496]])

In [135]:
np.random.random() # генерация случайного числа

0.43767262538051455

In [136]:
np.random.randint(5, 10) # генерация случайного числа в диапазоне [min, max)

5

In [137]:
np.random.poisson(6.0) # генерация числа, используя распределение Пуассона с λ = 6.0

4

In [138]:
np.random.normal(1.5, 4.0) # генерация числа с использованием нормального распределения (Гаусса) с μ = 1.5 и σ = 4.0

-1.5224080889736675

In [139]:
np.random.normal() # генерация числа с использованием нормального распределения (Гаусса) с μ = 0 и σ = 1

0.957100788846741

In [140]:
np.random.normal(size=5) # генерация нескольких значение, количество которых задается через size

array([-1.01092541,  0.58092445,  1.122653  , -0.1252049 ,  0.57716007])

In [141]:
l = [i for i in range(10)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [142]:
np.random.shuffle(l) # перемешивание значений списка
l

[7, 5, 2, 9, 4, 0, 8, 3, 6, 1]

### Список истоников
- https://habr.com/post/352678/
- https://habr.com/post/353416/
- https://habr.com/ru/post/413381/
- https://habr.com/ru/post/415373/
- https://engineering.ucsb.edu/~shell/che210d/numpy.pdf